/**
 * The two AI artifacts as REUSABLE JOBS: assemble the input, make ONE Claude
 * call, persist the result.
 *
 * This code used to be the top-level body of `run-brief.ts` and
 * `run-action-plan.ts`, which is precisely why both artifacts drifted — nothing
 * but a human at a terminal could reach it. It bit us once (docs/20 §D-2):
 * `/api/action-plan` kept serving "Restore brightness on 34 dark but online
 * screens" after the brightness verdict fix took recommendations from 34 to 11,
 * until someone regenerated by hand. Extracting the cores here lets the poller
 * daemon schedule the exact same code the npm scripts run — one prompt
 * assembly, one persistence path, no second copy to drift apart.
 *
 * Both jobs GENERATE first and PERSIST second, in a single INSERT. A failed call
 * therefore leaves the previously cached artifact untouched: a stale artifact is
 * honest as long as its age is disclosed, but a half-written one is a lie.
 */

import Anthropic from "@anthropic-ai/sdk";
import type { Pool } from "pg";
import { ReadQueries } from "../api/queries.js";
import { FleetContext } from "./context.js";
import { assembleBundle, summarizeIntelligence, type FleetBundle } from "./bundle.js";
import { generateFleetBrief, type FleetBrief } from "./brief.js";
import {
  generateActionPlan,
  summarizePersistedPop,
  type ActionPlan,
  type PlanInput,
  type PlanRollups,
} from "./action-plan.js";
import type { DeviceView } from "../intelligence/remediation.js";

/** Stamped into the persisted row. Kept a literal so the row records what ran. */
const MODEL = "claude-opus-5";

/**
 * What a job hands back: the artifact, plus the two numbers a caller needs to
 * report the run honestly (how much of the fleet it covered, what it cost).
 */
export interface AiJobOutcome<T> {
  artifact: T;
  windowHours: number;
  /** Fleet size the artifact was generated over — the run row's devicesTargeted. */
  devicesCovered: number;
  usage: Anthropic.Usage;
}

/**
 * Refuse to persist an artifact with nothing in it.
 *
 * An empty plan body reads as "nothing to do" and an empty brief reads as "the
 * fleet is fine" — both are the opposite of the truth when the real answer is
 * "generation produced nothing". Throwing here keeps the PREVIOUS artifact in
 * the cache, where its `generatedAt` at least tells the operator how old it is.
 *
 * `items: []` is deliberately NOT empty in this sense: a plan whose focus says
 * the data supported no actions is a legitimate result (renderActionPlan has a
 * line for it). Same for a brief with an empty needsAttention list.
 */
export function assertPublishableBrief(brief: FleetBrief): void {
  if (brief.headline.trim().length === 0 || brief.fleetState.trim().length === 0) {
    throw new Error(
      "Brief generation produced no headline or fleet state; refusing to persist it over the previous brief.",
    );
  }
}

export function assertPublishablePlan(plan: ActionPlan): void {
  if (plan.focus.trim().length === 0) {
    throw new Error(
      "Action plan generation produced no focus; refusing to persist it over the previous plan.",
    );
  }
}

export interface BriefJobOptions {
  windowHours?: number;
  /** Injectable so tests and the eval suite never touch the network. */
  client?: Anthropic;
}

/**
 * Generate a fleet brief and PERSIST it.
 *
 * The persist step is load-bearing: `GET /api/fleet/brief` serves the most
 * recent row from `briefs`, so a brief that is only printed to stdout leaves
 * that endpoint permanently empty. The bundle is stored alongside the output so
 * any claim in a brief can be traced back to the data it came from.
 */
export async function runBriefJob(
  pool: Pool,
  { windowHours = 24, client }: BriefJobOptions = {},
): Promise<AiJobOutcome<FleetBrief> & { bundle: FleetBundle }> {
  const bundle = await assembleBundle(new FleetContext(pool), new ReadQueries(pool), windowHours);
  const { brief, usage } = await generateFleetBrief(bundle, {
    windowHours,
    ...(client ? { client } : {}),
  });

  assertPublishableBrief(brief);

  await pool.query(
    `INSERT INTO briefs (window_hours, brief, bundle, model, input_tokens, output_tokens)
     VALUES ($1, $2::jsonb, $3::jsonb, $4, $5, $6)`,
    [
      windowHours,
      JSON.stringify(brief),
      JSON.stringify(bundle),
      MODEL,
      usage.input_tokens,
      usage.output_tokens,
    ],
  );

  return {
    artifact: brief,
    bundle,
    windowHours,
    devicesCovered: bundle.overview.totalDevices,
    usage,
  };
}

/**
 * The control-plane readers live in plan-inputs.ts and are imported ON DEMAND:
 * they pull in the credentialed HTTP client, which validates the whole
 * environment at import time. Keeping that import lazy is what lets this module
 * — and the scheduled lane wrapping it — be unit-tested with a stub client and
 * no .env, and it also means a run with `rollups` overridden never touches the
 * control plane at all.
 */
const defaultRollups = async (skipRollups: boolean): Promise<PlanRollups> =>
  (await import("./plan-inputs.js")).readPlanRollups(skipRollups);

const defaultResolveSites = async (devices: DeviceView[]): Promise<DeviceView[]> =>
  (await import("./plan-inputs.js")).withResolvedSites(devices);

export interface ActionPlanJobOptions {
  windowHours?: number;
  skipRollups?: boolean;
  client?: Anthropic;
  /** Both default to the control-plane readers above; overridden in tests. */
  rollups?: (skipRollups: boolean) => Promise<PlanRollups>;
  resolveSites?: (devices: DeviceView[]) => Promise<DeviceView[]>;
}

/**
 * Generate a prioritized action plan (US-5.2) and PERSIST it.
 *
 * Mirrors runBriefJob: assemble the structured intelligence, make ONE Claude
 * call, store the plan next to the input it was generated from. The persist step
 * is load-bearing for the same reason — `GET /api/action-plan` serves the most
 * recent `action_plans` row.
 */
export async function runActionPlanJob(
  pool: Pool,
  {
    windowHours = 24,
    skipRollups = false,
    client,
    rollups = defaultRollups,
    resolveSites = defaultResolveSites,
  }: ActionPlanJobOptions = {},
): Promise<AiJobOutcome<ActionPlan> & { input: PlanInput }> {
  const queries = new ReadQueries(pool);
  const fleet = new FleetContext(pool);

  const [overview, devices, persistedPop, planRollups] = await Promise.all([
    fleet.overview(),
    queries.remediationDevices(),
    queries.popPersistedSchedules(),
    rollups(skipRollups),
  ]);

  // Reuse the brief's fold verbatim so the two AI surfaces can never disagree
  // about what the engines said. Its own POP block is the batch-brief caveat
  // ("not measured"); the plan replaces it with the persisted fleet-wide gap
  // summary, which is one query and therefore cheap enough to carry here.
  const { remediation, correlation } = summarizeIntelligence(await resolveSites(devices));

  const input: PlanInput = {
    windowHours,
    overview,
    remediation,
    correlation,
    proofOfPlay: summarizePersistedPop(persistedPop.devices, persistedPop.fleetDevices),
    rollups: planRollups,
  };

  const { plan, usage } = await generateActionPlan(input, { ...(client ? { client } : {}) });

  assertPublishablePlan(plan);

  await pool.query(
    `INSERT INTO action_plans (window_hours, plan, input, model, input_tokens, output_tokens)
     VALUES ($1, $2::jsonb, $3::jsonb, $4, $5, $6)`,
    [
      windowHours,
      JSON.stringify(plan),
      JSON.stringify(input),
      MODEL,
      usage.input_tokens,
      usage.output_tokens,
    ],
  );

  return { artifact: plan, input, windowHours, devicesCovered: overview.totalDevices, usage };
}
